### ISSUE TITLE
Use variable and ansible specific task to deploy apt and yum repositories

### ISSUE THREAD

**Issue by ClementJ35** [Worteks/ansible-lemonldapng#18]
Hi,
I wrote an ansible role to deploy lemonldap, but it would be better to pool our efforts. Still, We don't use bare repositories but a custom one.
If this is acceptable, I already wrote a something and will submit a PR.

Regards,
Clément

**Comment by ClementJ35** [comment]
Here is my branch : [ClementJ35/ansible-lemonldapng:add_repository_as_vars](https://github.com/ClementJ35/ansible-lemonldapng/tree/add_repository_as_vars)

**Comment by l00ptr** [comment]
Hi @ClementJ35 ,

could you rebase and create a pull request ?

Best regards,
l.
