### ISSUE TITLE
Update to LL::NG 2.0

### ISSUE THREAD

**Issue by coudot** [Worteks/ansible-lemonldapng#2]
Some adaptations are needed to use LemonLDAP::NG 2.0

**Comment by l00ptr** [comment]
Could you tell me more about the required adaptations ? It seems to work with the latest version of LemonLDAP for me. Or maybe i miss something

**Comment by maxbes** [comment]
Some fixes were needed for RHEL. This is now fixed as of 4ddcb1fd1d1d03a96cbe74a626ec573d410be731
